# Generated by Django 4.2.7 on 2023-11-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha Eliminación')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha Eliminación')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha Eliminación')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre Producto')),
                ('description', models.TextField(verbose_name='Descripción Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha Eliminación')),
                ('descount_value', models.PositiveSmallIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsApp.categoryproduct', verbose_name='Indicador de Oferta')),
            ],
            options={
                'verbose_name': 'Indicador de Oferta',
                'verbose_name_plural': 'Indicadores de Ofertas',
            },
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsApp.measureunit', verbose_name='Unidad de Medida'),
        ),
    ]
